---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_bags_path: test/fixtures/data_bags
  encrypted_data_bag_secret_key_path: test/fixtures/encrypted_data_bag_secret
  product_name: chef
  product_version: 14.15.6

verifier:
  name: inspec

platforms:
  - name: debian-10.4
  - name: ubuntu-18.04
  - name: ubuntu-20.04
  - name: centos-7.8
  - name: centos-8.2
  - name: fedora-32
    run_list:
      - yum::dnf_yum_compat

suites:
  - name: default
    run_list:
      - recipe[test::default]
  - name: cluster-client
    driver:
      network:
        - - private_network
          - ip: 192.168.120.201
    includes:
      - centos-7.8
    run_list:
      - recipe[cluster::client]
  - name: cluster-server
    driver:
      network:
        - - private_network
          - ip: 192.168.120.101
        - - forwarded_port
          - guest: 4646
            host: 4646
    includes:
      - centos-7.8
    run_list:
      - recipe[cluster::server]
      - recipe[cluster::jobs]
